"""add role to users, extend jobs, add applications table

Revision ID: 08962a57408d
Revises: 382fdd9ee1da
Create Date: 2026-06-14 11:24:27.279271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08962a57408d'
down_revision: Union[str, None] = '382fdd9ee1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default='Applied', nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_job_candidate')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.add_column('jobs', sa.Column('source', sa.String(), server_default='external', nullable=False))
    op.add_column('jobs', sa.Column('recruiter_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('required_skills', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['recruiter_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(), server_default='candidate', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'required_skills')
    op.drop_column('jobs', 'recruiter_id')
    op.drop_column('jobs', 'source')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
