"""add interview questions to jobs and assessment to applications

Revision ID: 444d3cc2a6b4
Revises: d7cfca64f12a
Create Date: 2026-06-14 14:05:05.208506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444d3cc2a6b4'
down_revision: Union[str, None] = 'd7cfca64f12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('assessment_score', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('assessment_feedback', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('interview_questions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'interview_questions')
    op.drop_column('applications', 'assessment_feedback')
    op.drop_column('applications', 'assessment_score')
    # ### end Alembic commands ###
