"""add interview and assessment columns

Revision ID: 81aacfb75a4a
Revises: 444d3cc2a6b4
Create Date: 2026-06-14 14:06:05.884869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81aacfb75a4a'
down_revision: Union[str, None] = '444d3cc2a6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
