"""add score to resumes

Revision ID: 9e0b1bc16ba1
Revises: 08962a57408d
Create Date: 2026-06-14 13:00:37.095122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0b1bc16ba1'
down_revision: Union[str, None] = '08962a57408d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('score', sa.Integer(), nullable=True))
    op.drop_constraint('resumes_user_id_fkey', 'resumes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('resumes_user_id_fkey', 'resumes', 'users', ['user_id'], ['id'])
    op.drop_column('resumes', 'score')
    # ### end Alembic commands ###
